export const promise = {
  PENDING: '_PENDING',
  REJECTED: '_REJECTED',
  FULFILLED: '_FULFILLED',
};

export const userActionsTypes = {
  LOADING_USER: 'LOADING_AUTHENTICATION_USER',
  LOG_IN: 'LOG_IN_USER',
  LOG_OUT: 'LOG_OUT_USER',
};

export const buildings = {
  GET_BUILDING_DATA: 'GET_BUILDING_DATA',
  SET_SELECTED_BUILDING: 'SELECT_BUILDING',
};

export const doorStation = {
  SET_SELECTED_DOOR_STATION: 'SET_SELECTED_DOOR_STATION',
};

export const operators = {
  GET_OPERATORS_INFO: 'GET_OPERATORS_INFO',
};

export const notification = {
  ACCEPT_NOTIFICATION: 'ACCEPT_NOTIFICATION',
  REGENERATE_NOTIFICATION: 'REGENERATE_NOTIFICATION',
  RESOLVE_NOTIFICATION: 'RESOLVE_NOTIFICATION',
  SET_NOTIFICATION: 'SET_NOTIFICATION',
};

export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
