export const promise = {
  PENDING: '_PENDING',
  REJECTED: '_REJECTED',
  FULFILLED: '_FULFILLED',
};

export const socketTypes = {
  CONNECTING_TO_SERVER: 'CONNECTING_TO_SERVER',
  CONNECTION_REJECTED: 'SERVER_REJECTED_CONNECTION',
  SERVER_CONNECTED: 'SERVER_CONNECTED',
  SERVER_DISCONNECTED: 'SERVER_DISCONNECTED',
};

export const usersActionsTypes = {
  SET_LOGGED_USER: 'SET_LOGGED_USER',
  SET_USERS: 'SET_LIST_OF_USERS',
};

export const buildings = {
  GET_BUILDING_DATA: 'GET_BUILDING_DATA',
  SET_SELECTED_BUILDING: 'SELECT_BUILDING',
};

export const doorStation = {
  SET_SELECTED_DOOR_STATION: 'SET_SELECTED_DOOR_STATION',
};


export const notification = {
  ACCEPT_NOTIFICATION: 'ACCEPT_NOTIFICATION',
  REGENERATE_NOTIFICATION: 'REGENERATE_NOTIFICATION',
  RESOLVE_NOTIFICATION: 'RESOLVE_NOTIFICATION',
  SET_NOTIFICATION: 'SET_NOTIFICATION',
};

export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
